# Generated by Django 4.0.3 on 2022-04-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
