# Generated by Django 4.0.3 on 2022-04-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'last_name', 'birth_date')},
        ),
    ]
