# Generated by Django 4.0.3 on 2022-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='courses',
        ),
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
