# Generated by Django 4.0.3 on 2022-04-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
