# Generated by Django 4.0.3 on 2022-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_person_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='courses',
        ),
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.course'),
        ),
    ]
