# Generated by Django 4.0.3 on 2022-04-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_person_courses_person_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
