# Generated by Django 4.0.3 on 2022-04-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_person_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
